import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  drawerButton: {
    width: '90%',
    height: 50,
    margin: '10px 5%',
    backgroundColor: '#fff',
    borderRadius: 10,
    justifyContent: 'center',
    paddingLeft: 10,
    elevation: 3,
  },
  drawerButtonText: {
    fontSize: 16,
    color: '#000000',
    fontFamily: 'Lato-Regular',
  },
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
  },
  fecharTexto: {
    fontSize: 30,
    color: '#000000',
    fontFamily: 'Lato-Regular',
  },
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
  },
  image: {
    width: 191,
    height: 71.63,
    marginBottom: 50,
  },
  textLogin: {
    fontSize: 18,
    marginBottom: 20,
    position: 'absolute',
    marginRight: Platform.OS !== 'web' ? 100 : '69%',
    // fontFamily: 'Inter-Bold',
    color: '#484848',
  },
  input: {
    width: '80%',
    marginBottom: 20,
  },
  textInput: {
    height: 40,
    borderWidth: 1,
    borderColor: '#ccc',
    marginBottom: 20,
    paddingLeft: 10,
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 5,
    // fontFamily: 'Inter-Regular',
    fontStyle: 'italic',
  },
  loginButton: {
    width: '80%',
    height: 58,
    borderRadius: 10,
    backgroundColor: '#00005D',
    padding: 10,
    borderWidth: 1,
    borderColor: '#00000033',
    shadowColor: '#000',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
  },
  loginButtonText: {
    color: '#fff',
    textAlign: 'center',
    fontSize: 16,
    marginTop: 5,
    // fontFamily: 'Inter-Bold',
  },
  viewSign: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'fixed',
    top: 180,
  },
  header: {
    backgroundColor: '#00005D',
    padding: 30,
    width: '100%',
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  scrollContainer: {
    flex: 1,
    width: '100%',
  },
  backButton: {
    padding: 10,
    borderRadius: 50,
  },
  backButtonImage: {
    width: 30,
    height: 30,
  },
  fakeInput: {
    height: 40,
    borderColor: '#ccc',
    borderWidth: 1,
    marginBottom: 20,
    padding: 5,
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    borderRadius: 10,
  },
  containerBotao: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    width: '100%',
    paddingRight: 10,
  },
  botaoMf: {
    width: 20,
    padding: 5,
    backgroundColor: (props) => (props.selected ? '#00005D' : '#DDDDDD'),
    borderRadius: 5,
    marginHorizontal: 5,
  },
  falsoInputTexto: {
    fontSize: 14,
    color: '#565656',
    position: 'absolute',
    left: 10,
    top: 10,
    // fontFamily: 'Inter-Regular',
  },
  textoMf: {
    color: (props) => (props.selected ? '#FFFFFF' : '#000000'),
    fontWeight: 'bold',
    fontSize: 12,
    textAlign: 'center',
    // fontFamily: 'Inter-Regular',
  },
  espacoPicker: {
    height: 40,
    width: '100%',
    borderWidth: 1,
    borderColor: '#ccc',
    marginBottom: 20,
    paddingLeft: 100,
    paddingBottom: 5,
    paddingTop: 5,
    borderRadius: 10,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 4,
    elevation: 5,
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  estadoCivil: {
    height: 40,
    width: '100%',
    // fontFamily: 'Inter-Regular',
    alignItems: 'center',
  },
  pickerTexto: {
    position: 'absolute',
    left: 3,
    top: 5,
    fontSize: 15,
    color: '#565656',
    backgroundColor: '#fff',
    padding: '5px 10px',
    fontStyle: 'italic',
  },
  pickerItem: {
    alignSelf: 'center',
  },
  textSignup: {
    fontSize: 14,
    // fontFamily: 'Inter-Regular',
  },
  signup: {
    // Estilos adicionais, se necessário
  },
  viewAzul: {
    flex: 1,
    backgroundColor: '#00005D',
  },
  viewTopo: {
    width: '100%',
    height: '45%',
    backgroundColor: '#00005D',
    justifyContent: 'center',
    alignItems: 'center',
  },
  viewBranco: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    padding: 20,
    marginTop: -30,
  },
  viewBotao: {
    flex: 1,
    height: 400,
    alignItems: 'center',
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    padding: 3,
    marginPadding: 10,
  },
  opcaoImage: {
    width: 35,
    height: 35,
  },
  logoIesgo: {
    width: 280,
    height: 108,
    tintColor: '#FFFFFF',
    marginTop: 60,
  },
  imagemBotao: {
    width: 40,
    height: 40,
  },
  imagemPerfil: {
    position: 'relative',
    left: 150,
    width: 45,
    height: 45,
    borderRadius: 20,
  },
  botaoServico: {
    width: 100,
    height: 100,
    borderWidth: 1,
    borderColor: '#ccc',
    borderRadius: 10,
    elevation: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    marginTop: 30,
  },
  botaoOpcao: {
    position: 'absolute',
    top: 60,
    left: 15,
  },
  textoBotao: {
    textAlign: 'center',
    fontSize: 12,
    // fontFamily: 'Inter-Regular',
  },
  textoHome: {
    position: 'absolute',
    fontSize: 20,
    color: '#FFFFFF',
    marginTop: 20,
    left: 15,
    top: 90,
    fontFamily: 'Lato-Regular',
  },
  textoHomeBranco: {
    fontSize: 20,
    color: '#000000',
    // fontFamily: 'Inter-Regular',
  },
  textoFisio: {
    fontSize: 36,
    color: '#FFFFFF',
    textAlign: 'center',
    marginLeft: 10,
    // fontFamily: 'Inter-Bold',
  },

});
